describe('template spec', () => {
  beforeEach(function() {
    cy.visit('http://stghrms.paxanimi.ai/').wait(4000)
      cy.get('#basic_userEmail').type("comp1-superad@mailinator.com").wait(3000)
      cy.get('#basic_password').type("12345678@Tc").wait(3000)
      cy.get("button[type='submit'] div[class='button-content']").click().wait(90000)
      cy.get(".logoText___2I_bK").should('have.text', 'HR-OS')
      cy.get(':nth-child(2) > .viewAction___2wj7D > .btnOutline___3sCPv > span').click({force:true})
  })  
    it('in admin page company details', () => {
      //cy.visit('http://stghrms.paxanimi.ai/').wait(4000)
      //cy.get('#basic_userEmail').type("comp1-superad@mailinator.com").wait(3000)
      //cy.get('#basic_password').type("12345678@Tc").wait(3000)
     // cy.get("button[type='submit'] div[class='button-content']").click().wait(90000)
      //cy.get(".logoText___2I_bK").should('have.text', 'HR-OS')
      //cy.get("div[class='companiesContainer___3Yqdu'] div:nth-child(2) div:nth-child(2) button:nth-child(1)").click()
      cy.get(".CustomSinglePage__header__left__title___2ojBK").should('have.text','Admin App')
      cy.get(':nth-child(1) > .content__viewTop___1jVyH > .editBtn___pR87U > .wrapBtn___2P4t2 > span').click()
      cy.get('#industry').type("Information Technology")//cy.get(' #basic_tasks_0_startTime').type('9:30 am',{ force: true })
        .type('{enter}', {force:true})
      cy.get('#companyType').type("product")
       .type('{enter}')
      cy.get('#name').type("IT")
      cy.get('#dba').type("Tester")
      cy.get('#ein').type(3011)
      cy.get('#website').type("ghddhgfdhf.com")
      cy.get('#parentCompany').type("IT Head office")

      })
    it.skip("verifying the Head quaters address",()=>{
      cy.visit('http://stghrms.paxanimi.ai/').wait(4000)
      cy.get('#basic_userEmail').type("comp1-superad@mailinator.com").wait(3000)
      cy.get('#basic_password').type("12345678@Tc").wait(3000)
      cy.get("button[type='submit'] div[class='button-content']").click().wait(90000)
      cy.get(".logoText___2I_bK").should('have.text', 'HR-OS')
      cy.get(':nth-child(2) > .viewAction___2wj7D > .btnOutline___3sCPv > span').click({force:true})
      cy.get(':nth-child(2) > :nth-child(1) > .editBtn___pR87U > .wrapBtn___2P4t2 > span').click({force:true})
      cy.get('#headquarterAddressLine1').type("13-1-256, mg olony")
      cy.get('#headquarterAddressLine2').type("3rd cross")
      cy.get('#cityHeadquarter').type("Anantapur")
      cy.get("#countryHeadquarterProps").click().type("Ind")
      cy.get("div[title='India'] div[class='ant-select-item-option-content']").click({force:true})
      cy.contains("India").click({force:true})
      cy.get(' #stateHeadquarter').type('Andhra Pradesh', { force: true })
        .type('{enter}', { force: true }, ).wait(7000)
      cy.get('#zipHeadquarter').type("515001")
      cy.get('.ant-checkbox-input').check()

    })
    it.only("",()=>{
      cy.get(':nth-child(3) > .content__viewTop___1jVyH > .editBtn___pR87U > .wrapBtn___2P4t2 > span').click()
      cy.get('#ownerEmail').clear()
        .type("gsfdhgfjhdgf")
      cy.get('#hrName').type("hghsgd")
      cy.get('#hrEmail').type("ykuyuygu")
      cy.get('#hrPhone').type(67686868)
      //cy.get('.viewBtn___1rCSB > .ant-btn') to save final data
    })
    })
